[package]
authors = ["Catiumeye"]
name = "neko-image"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
description = "CLI utility for image processing written in rustğŸ³ï¸â€âš§ï¸"

[[bin]]
name = "neko-image"
path = "src/main.rs"

[dependencies]
arboard = "3.3.1"
clap = "4.4.8"
color-print = "0.3.5"
image = "0.24.7"
lazy_static = "1.4.0"
